### ISSUE TITLE
Paging Error

### ISSUE THREAD

**Issue by zoilomora** [zoilomora/doctrine-dbal-msaccess#1]
https://github.com/zoilomora/laravel-msaccess/issues/7

**Comment by zoilomora** [comment]
This change fixes the **LIMIT** but not the **OFFSET**: https://github.com/mpk-software/doctrine-dbal-msaccess/commit/19633d689ee77bec65d8537dbe288e82b213c16d

**Comment by zoilomora** [comment]
@marioklump Do you want to make the change or will I upload it?

**Comment by zoilomora** [comment]
@marioklump According to this [answer](https://stackoverflow.com/a/8627332) **MS Access does not carry any OFFSET functionality**. Perhaps the appropriate thing would be to disable it at the [platform level](https://github.com/doctrine/dbal/blob/2.12.x/lib/Doctrine/DBAL/Platforms/SQLServerPlatform.php#L1418).

**Comment by mario-van-zadel** [comment]
@zoilomora thank you for making your repository available again. Please feel free to reintegrate https://github.com/mpk-software/doctrine-dbal-msaccess/commit/19633d689ee77bec65d8537dbe288e82b213c16d into your repository. Unfortunately, I'm not able to create a pull-request because the fork-link between your repo and my fork has disappeared at the time you deleted/archived your repo. Are you able to cherry-pick the commit https://github.com/mpk-software/doctrine-dbal-msaccess/commit/19633d689ee77bec65d8537dbe288e82b213c16d?

Cherry-pick from another repo: https://stackoverflow.com/a/5120074/3647441

> @marioklump According to this [answer](https://stackoverflow.com/a/8627332) **MS Access does not carry any OFFSET functionality**. Perhaps the appropriate thing would be to disable it at the [platform level](https://github.com/doctrine/dbal/blob/2.12.x/lib/Doctrine/DBAL/Platforms/SQLServerPlatform.php#L1418).

I agree with you. If the feature isn't supported, we should disable this feature at the platform level.

**Comment by zoilomora** [comment]
@marioklump thanks for answering! after deleting the original repository... everything has gone into a mess!

Could you create a new pull request, committing the changes again? **I would like your contribution to the repository not to be lost**.

> I agree with you. If the feature isn't supported, we should disable this feature at the platform level.

I'm going to add that restriction right now!

**Comment by mario-van-zadel** [comment]
@zoilomora I created two pull requests for the changes I've done at the beginning of the year.

Am I right that we don't need https://github.com/mpk-software/doctrine-dbal-msaccess-deprecated/commit/19633d689ee77bec65d8537dbe288e82b213c16d anymore after disabling the limit+offset feature in https://github.com/zoilomora/doctrine-dbal-msaccess/pull/6/commits/1e38244c7c3a162024be490b5864b335ff4166b0#diff-f0064b158706fcfce932aac43a1e57a0cf0a19e8e2446a1da53760d80a41cc93 ?

**Comment by zoilomora** [comment]
@marioklump No, setting `supportsLimitOffset=false` lock the use of the **offset**, not the **limit**.

For the **limit** if your changes that add **TOP** in the SQL query are needed.
